# Generated by Django 3.2.9 on 2021-12-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user_avatar',
        ),
    ]
