# Generated by Django 3.2.9 on 2021-12-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_remove_card_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='createdDate',
            new_name='time_stamp',
        ),
        migrations.RenameField(
            model_name='postview',
            old_name='createdDate',
            new_name='time_stamp',
        ),
    ]
