# Generated by Django 3.2.9 on 2021-12-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20211206_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['id']},
        ),
    ]
